### ISSUE TITLE
[Bug]: Large number of content files breaks command line

### ISSUE THREAD

**Issue by buddhist-uni** [FullHuman/purgecss#1155]
### Describe the bug

Recently tried upgrading node from 18.7 and suddenly wasn't able to run `npx purgecss ...` as before. With any node version >= 18.8, I now get:

```
npm ERR! Cannot read properties of undefined (reading 'stdin')
```

The full stack trace (below) doesn't mention your code at all so I think this is a bug with a large size of command-line arguments overloading the npm spawner?   Mostly posting the issue here to get everyone's ideas on how best to resolve this issue (and for the sake of future people stuck on this bug):

```
34 verbose stack TypeError: Cannot read properties of undefined (reading 'stdin')
34 verbose stack     at promiseSpawn (~/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:60:18)
34 verbose stack     at spawnWithShell (~/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:123:10)
34 verbose stack     at promiseSpawn (~/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
34 verbose stack     at runScriptPkg (~/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:79:13)
34 verbose stack     at runScript (~/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:16)
34 verbose stack     at run (~/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/libnpmexec/lib/run-script.js:63:18)
34 verbose stack     at async exec (~/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:137:16)
34 verbose stack     at async module.exports (~/.nvm/versions/node/v18.16.1/lib/node_modules/npm/lib/cli.js:134:5)
```

### To Reproduce

When I run:

```
npx purgecss --content _site/content/*/*.html --css _site/assets/css/main.css --output assets/css/purged.css
```

on my rather large site (thousands of html files) I get the error.  Trying each `_site/content/` folder _separately_ did not cause the error, so I'm thinking there must be some issue with the number of command line arguments being passed?

### Expected Behavior

Works as it does in node 18.7

### Environment

I'm using nvm to manage node versions on an Ubuntu machine, but this behavior was verified on a non-nvm machine as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by buddhist-uni** [comment]
Oh! Okay, I solved my issue. It seems your argument parser is smart enough to take globs directly!  So I can do `--content '_site/**/*.html'` in single quotes so that bash doesn't expand the glob and that solved the issue.

Perhaps worth updating [the CLI documentation](https://purgecss.com/CLI.html#content) by putting the glob pattern in `'`s so other purgecss users with large sites don't get burned by this as well :smile_cat:
