### ISSUE TITLE
Unable to use the CLI: it always displays the help message

### ISSUE THREAD

**Issue by j0k3r** [FullHuman/purgecss#260]
I would like to try this tool but I was unable to get sth using the CLI.

My project is a dead simple jekyll.

```
/
├── _site
│   └── assets
│       └── css
│          └── main.css
│   └── index.html
│   └── post1.html
│   └── post2.html
```

All these commands dumped the help message:

```bash
j0k@MBP:~/blog$ npx purgecss --css _site/assets/css/main.css --content _site/*.html
npx : 27 installé(s) en 3.081s
Usage: purgecss --css <css> --content <content> [options]

Options:
  -con, --content  glob of content files
  -css, --css      glob of css files
  -c, --config     path to the configuration file
  -o, --output     file path directory to write purged css files to
  -w, --whitelist  list of classes that should not be removed
  -h, --help       output usage information
```

```bash
j0k@MBP:~/blog$npm install -g purgecss
blablabla
j0k@MBP:~/blog$ purgecss --css _site/assets/css/main.css --content _site/*.html
Usage: purgecss --css <css> --content <content> [options]

Options:
  -con, --content  glob of content files
  -css, --css      glob of css files
  -c, --config     path to the configuration file
  -o, --output     file path directory to write purged css files to
  -w, --whitelist  list of classes that should not be removed
  -h, --help       output usage information
```

Quickly looking at the `bin/purgecss` file and it seems I must pass a config file, so I tried with that one:

```js
module.exports = {
  content: ['_site/*.html'],
  css: ['_site/assets/css/main.css']
}
```

And same result:

```bash
j0k@MBP:~/blog$ purgecss --config purgecss.config.js
Usage: purgecss --css <css> --content <content> [options]

Options:
  -con, --content  glob of content files
  -css, --css      glob of css files
  -c, --config     path to the configuration file
  -o, --output     file path directory to write purged css files to
  -w, --whitelist  list of classes that should not be removed
  -h, --help       output usage information
```

I tried to combine all information and then got an error:

```bash
j0k@MBP:~/blog$ purgecss --css _site/assets/css/main.css --content _site/*.html --config purgecss.config.js
(node:23298) UnhandledPromiseRejectionWarning: Error: Error loading the config file The "path" argument must be of type string. Received type boolean
    at setOptions (/Users/j0k/.nvm/versions/node/v12.14.1/lib/node_modules/purgecss/lib/purgecss.js:1:2233)
    at /Users/j0k/.nvm/versions/node/v12.14.1/lib/node_modules/purgecss/bin/purgecss:27:21
    at Object.<anonymous> (/Users/j0k/.nvm/versions/node/v12.14.1/lib/node_modules/purgecss/bin/purgecss:49:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
(node:23298) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23298) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Did I make something wrong?

I'm running:
- macOS Mojave
- node 12.14.1 (installed using nvm)
- latest purgecss I guess (there is no `--version` option to the cli)

**Comment by jannisborgers** [comment]
Same for me. I tried all combinations of CLI commands, but even a basic command where only `--css` and `--content` are set return the usage instructions instead of the expected output of results. Config file didn’t change anything when used with `--config`. I couldn’t even get purgecss to throw an error by using a non-existing file name for the `--css` path. The library just does… nothing.

What I noticed is that the usage instructions tell me to use `--output`, while the documentation uses `--out`. I focused on that, but I think the issue itself has nothing to do with this option directly.

Using:
- macOS Catalina 10.15.2
- Node 12.14.1
- purgecss ^2.0.3

**Comment by Ffloriel** [comment]
There was an issue with the CLI. The version 2.0.5 should have fixed the issue

**Comment by jannisborgers** [comment]
2.0.5 has solved the issue for me.

**Comment by j0k3r** [comment]
Yup it's fixed thanks!
