### ISSUE TITLE
TypeError: Class constructor extractor cannot be invoked without 'new'

### ISSUE THREAD

**Issue by simllll** [FullHuman/purgecss#274]
I just updated @fullhuman/purgecss to the latest version, and experience a weird issue now while using this inside of a nuxt typescript built:

```js
TypeError: Class constructor extractor cannot be invoked without 'new'
    at extractSelectors (/home/simon/Dev/hokify/hokify-frontend/node_modules/purgecss/lib/purgecss.js:1:2358)
    at PurgeCSS.extractSelectorsFromFiles (/home/simon/Dev/hokify/hokify-frontend/node_modules/purgecss/lib/purgecss.js:1:5802)
    at async /home/simon/Dev/hokify/hokify-frontend/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:501
```

Versions:
purgecss 2.0.5
@fullhuman/postcss-purgecss@2.0.5

**Comment by simllll** [comment]
https://github.com/FullHuman/postcss-purgecss/issues/57

**Comment by Ffloriel** [comment]
https://github.com/FullHuman/purgecss/issues/276

**Comment by Ffloriel** [comment]
The extractor is now a function that takes the content as an argument.
```js
class Extractor {
    static extract(content) {}
}
```
changes to
```js
function extractor(content) {}
```
