### ISSUE TITLE
EOF Error being raised in v2.2.0

### ISSUE THREAD

**Issue by cvarley** [FullHuman/purgecss#405]
Running as part of the build process for a dotnetcore 3.1 project - if version **2.1.2** is specified
`npm -i purgecss@2.1.2 `
and then run command 
`purgecss --config purgecss.config.js --output wwwroot/css`
purgecss works as expected. 

However if version **@2.2.0** is specified, an EOF error results. 

```
+ purgecss@2.2.0
  updated 1 package in 7.325s
  fs.js:114
      throw err;
      ^

EXEC : error : EOF: end of file
      at Object.readSync (fs.js:498:3)
      at tryReadSync (fs.js:332:20)
      at Object.readFileSync (fs.js:369:19)
      at Object.<anonymous> (<dir>\node_modules\purgecss\bin\purgecss:31:21)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
ed with code 1.

error MSB3073: The command "purgecss --config purgecss.config.js --output wwwroot/css" exited with code 1.
```

**Comment by frederikhors** [comment]
After upgrading from `2.1.2` to `2.2.0` the same command throws an error:

```bash
fs.js:177
  return (stats[1/* mode */] & S_IFMT) === fileType;
               ^

TypeError: Cannot read property '1' of undefined
    at isFileType (fs.js:177:16)
    at Object.readFileSync (fs.js:363:16)
    at Object.<anonymous> (C:\alex\node_modules\purgecss\bin\purgecss:31:21)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

- Command:

`npx purgecss --css public\main.css --content public\main.html,public\main.js -o bundle`

**Comment by Ffloriel** [comment]
should be fixed in 2.2.1.
@cvarley , @frederikhors 
which OS are you using?

**Comment by cvarley** [comment]
Hi - this machine is Windows 10 Home 64-bit (version 1909 - build 18363.778)

**Comment by benoliver999** [comment]
FWIW I was getting a silent failure in my jekyll setup with 2.2.0.

2.2.1 seems to have fixed it before I could even start debugging! Thanks!

**Comment by cvarley** [comment]
Brilliant Thanks!
