### ISSUE TITLE
Error: Unexpected '/' in purgecss cli

### ISSUE THREAD

**Issue by sameerthekhans** [FullHuman/purgecss#440]
SCSS single line comments are not being recognized

In `css` `//` (double forward slash) comments are invalid, where as in `sass` or `scss` is valid

I have this file

*style.scss*
```
//This is a comment
.used {
 background: blue;
}

.not-used {
 background: red;
}

.not-used-2 {
 background: red;
}
```

when I run below command
`purgecss --css style.scss --content src/index.html --output build`

I got this error
```
(node:14876) ExperimentalWarning: The fs.promises API is experimental
(node:14876) UnhandledPromiseRejectionWarning: Error: Unexpected '/'. Escaping special characters with \ may help.
    at Root._error (/usr/local/lib/node_modules/purgecss/node_modules/postcss-selector-parser/dist/parser.js:160:16)
    at Root.error (/usr/local/lib/node_modules/purgecss/node_modules/postcss-selector-parser/dist/selectors/root.js:43:19)
    at Parser.error (/usr/local/lib/node_modules/purgecss/node_modules/postcss-selector-parser/dist/parser.js:726:21)
    at Parser.unexpected (/usr/local/lib/node_modules/purgecss/node_modules/postcss-selector-parser/dist/parser.js:744:17)
    at Parser.combinator (/usr/local/lib/node_modules/purgecss/node_modules/postcss-selector-parser/dist/parser.js:642:12)
    at Parser.parse (/usr/local/lib/node_modules/purgecss/node_modules/postcss-selector-parser/dist/parser.js:1081:14)
    at Parser.loop (/usr/local/lib/node_modules/purgecss/node_modules/postcss-selector-parser/dist/parser.js:1023:12)
    at new Parser (/usr/local/lib/node_modules/purgecss/node_modules/postcss-selector-parser/dist/parser.js:150:10)
    at Processor._root (/usr/local/lib/node_modules/purgecss/node_modules/postcss-selector-parser/dist/processor.js:55:18)
    at Processor._runSync (/usr/local/lib/node_modules/purgecss/node_modules/postcss-selector-parser/dist/processor.js:102:21)
(node:14876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And If I remove this `//This is a comment` then It works as expected

**Comment by Ffloriel** [comment]
PurgeCSS works with a valid CSS file. It will not work with preprocessed CSS like scss/sass, stylus...
You will need to process the sass file before and use the result with PurgeCSS. https://github.com/sass/node-sass#usage-1

The command might look like:
```
node-sass style.scss style.css && purgecss --css style.css --content src/index.html --output build
```
