### ISSUE TITLE
@fullhuman/postcss-purgecss causes an error when used with postcss.config.js and postcss-cli

### ISSUE THREAD

**Issue by Everspace** [FullHuman/purgecss#507]
Whenever I go to `yarn postcss ./_site/**/*.css --replace` I get an error 

```shell
$ Z:\git\blerg\node_modules\.bin\postcss ./_site/**/*.css --replace
TypeError: t is not a function
    at b (Z:\git\blerg\node_modules\purgecss\lib\purgecss.js:1:3509)
    at U.extractSelectorsFromFiles (Z:\git\blerg\node_modules\purgecss\lib\purgecss.js:1:5551)
    at async Z:\git\blerg\node_modules\@fullhuman\postcss-purgecss\lib\postcss-purgecss.js:1:571
    at async LazyResult.runAsync (Z:\git\blerg\node_modules\postcss\lib\lazy-result.js:331:11)
    at async Promise.all (index 2)
error Command failed with exit code 1.
```

One of the other things I noticed was a type error:

```
This expression is not callable.
  Type 'typeof import("z:/git/blerg/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss")' has no call signatures.
```
And using say, `import` nor `.default` worked.

## Info

- Platform: Windows 
- Node version: `14.10.1` 
- Yarn version `1.22.5`

```json
// package.json
{
 "devDependencies": {
    "@fullhuman/postcss-purgecss": "^3.0.0",
    "autoprefixer": "^10.0.1",
    "postcss": "^8.1.2",
    "postcss-cli": "^8.1.0",
    "purgecss": "^3.0.0",
  }
}
```
```js
//postcss.config.js
const purgecss = require("@fullhuman/postcss-purgecss");

class TailwindExtractor {
  static extract(content) {
    return content.match(/[A-Za-z0-9-_:\/]+/g) || [];
  }
}

module.exports = {
  plugins: [
    purgecss({
      content: ["./_site/**/*.html"],
      extractors: [ { extractor: new TailwindExtractor(), extensions: ["css", "html"] } ],
    })
  ]
};
```

**Comment by Ffloriel** [comment]
`extractor` is expected to be a function in recent versions. I would recommend looking at the TailwindCSS documentation. 
https://tailwindcss.com/docs/controlling-file-size#removing-unused-css

**Comment by Everspace** [comment]
@Ffloriel The problem is that I was hoping to do it with the cli, and I was confused as to why this was happening.

This was to hopefully do purge-css post-generation of rendered markdown (like from jekyll or in this case, eleventy) where tailwind's natural purgecss integration doesn't really work out and I was really trying to avoid pulling in webpack.

**Comment by PixelsCommander** [comment]
@Everspace did the suggestion worked?
