### ISSUE TITLE
PurgeCSS throws vague error if output is an array

### ISSUE THREAD

**Issue by liam-edwards** [FullHuman/purgecss#714]
**Describe the bug**
Running PurgeCSS through the CLI throws an error:

```
(node:9978) UnhandledPromiseRejectionWarning: TypeError: output.endsWith is not a function
    at run (/usr/local/lib/node_modules/purgecss/bin/purgecss.js:73:39)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9978) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Command ran: `purgecss -c purgecss.config.js`

Config file:

```
module.exports = {
    content: ['**/*.php', '**/*.js'],
    css: ['public/css/app.css'],
    output: ['public/purged-css'],
    safelist: ["a long", "list of classes"],
}
```

**To Reproduce**
1. Install purgecss globally (`npm i -g purgecss`)
2. Save the above config file
3. Run `purgecss -c purgecss.config.js`

**Expected behavior**
No errors and for the purge to run

**Environment (please complete the following information):**
 - OS: OSX 11.4
 - Node: 14.16.1
 - Package purgecss
 - Version 4.0.3

**Comment by liam-edwards** [comment]
Upon updating Node to v16.4.2, the error has changed:
```
/usr/local/lib/node_modules/purgecss/bin/purgecss.js:73
    if (purged.length === 1 && output.endsWith(".css")) {
                                      ^

TypeError: output.endsWith is not a function
    at run (/usr/local/lib/node_modules/purgecss/bin/purgecss.js:73:39)
```

**Comment by liam-edwards** [comment]
Just realised that output needs to be a string and not an array of strings. What I was looking at as a reference was either old or just wrong.
Either way, there should possibly be a check for that and throw a more suitable error.
